# Build szakasz
FROM maven:3.8.4-openjdk-17 AS build

WORKDIR /project

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src/ /project/src

RUN mvn package

# Második szakasz
FROM openjdk:18.0.1-jdk-slim

RUN mkdir /app

COPY --from=build /project/target/Szoftverfejlesztes-mernokoknek-0.0.1-SNAPSHOT.jar /app/app.jar

COPY src/main/resources/data.json resources/data.json

WORKDIR /app

EXPOSE 8000

CMD java $JAVA_OPTS -jar app.jar --spring.profiles.active=production