name: React App Workflow

on:
  pull_request:
    branches: [main]
    paths:
      - 'app/**' # Az app mappát figyeli
      - '.github/workflows/react-workflow.yaml'
  push:
    branches: [main]
    paths:
      - 'app/**' # Az app mappát figyeli
      - '.github/workflows/react-workflow.yaml'

jobs:
  react-app-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Node.js dependencies
        working-directory: app
        run: npm install

      - name: Run React App tests
        working-directory: app
        run: npm test

      - name: Build React App
        working-directory: app
        run: npm run build

  dockerize-and-deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - react-app-build

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-app-react # A Dockerfile elérési útja az app mappában lehet
          push: true
          tags: vlevente2001/sfm-react:latest

      - name: Deploy the application
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          set -e
          ./deploy_react.sh

